# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-11-28 04:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20190504_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='user',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
